POST /report HTTP/1.1
Host: localhost:3000
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="massive-transactions.csv"
Content-Type: text/csv

< ./testes/massive-transactions.csv
--boundary--

###
GET /report HTTP/1.1
Host: localhost:3000

###
GET /report/report-2026-05-10T20:59:56.141Z/dowload HTTP/1.1
Host: localhost:3000
